siteName: Innings2
description: A new approach to education
domain: innings2.com

privacyURL: /policies
banner: (c) Innings2
locales: [en, ar, cn, de, es, fr, hi, hr, it, ja, pt, ro, ru, sv, tr, vi]

search:
  enabled: false

header:
  titleString: Innings2
footer:
  rows:
    - links:
        - title: GitHub
          url: https://github.com/mathigon/textbooks
        - title: Live Website
          url: https://mathigon.org/courses
  copyright: © Innings2, 2022

social:
  facebook: {}
  twitter: {}

courses:
  showLocked: true
  revealAll: false
  audio: false

tutor:
  enabled: true
